disabled_rules:
  - function_parameter_count
  - nesting
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - line_length
  - missing_docs
  - opening_brace
  - closing_brace
  - return_arrow_whitespace
  - statement_position
  - todo
  - type_body_length
  - type_name
  - valid_docs
  - variable_name
  - variable_name_min_length
included:
  - Sources
excluded:
  - Pods
